### ISSUE TITLE
Token Key Attribute

### ISSUE THREAD

**Issue by aiopsdata** [damklis/DataEngineeringProject#62]
Hi,
I have successfully generated the Token for myself. The next step is to include token in header of request. What is the key attribute for token header?

**Comment by mbiombani** [comment]
<img width="629" alt="Postman" src="https://user-images.githubusercontent.com/14925384/138189136-37328d6d-f5d1-43e5-99d3-96a78e884996.png">


On Postman

**Comment by aiopsdata** [comment]
Thanks @mbiombani, Its working.
